name: Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Download SDL
      run: ./tools/sdl_download.sh

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v2

    - name: create android studio project / gradlew build
      run: |
          mkdir build_gradle_project
          cd build_gradle_project
          export ANDROID_HOME=/usr/local/lib/android/sdk
          cmake .. -DHELLOIMGUI_CREATE_ANDROID_STUDIO_PROJECT=ON
          cd hello_imgui_demodocking_AndroidStudio
          ./gradlew build
