name: Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install needed libraries
      run: sudo apt-get install -y openjdk-8-jdk-headless

    - name: Download Android NDK
      run: |
          mkdir toolchains
          cd toolchains
          wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
          unzip android-ndk-r21d-linux-x86_64.zip
          cd ..

    - name: Setup env variables
      run : |
          export ANDROID_NDK_HOME=$(pwd)/toolchains/android-ndk-r21d
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          ls $ANDROID_NDK_HOME

          which java
          java -version
          which javac
          echo "JAVA_HOME=$JAVA_HOME"

#    - name: Configure
#      run: |
#          mkdir build
#          cd build
#          cmake \
#                -DCMAKE_BUILD_TYPE=Release \
#                -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake \
#                -DHELLOIMGUI_USE_SDL_OPENGL3=ON  \
#                -DHELLOIMGUI_USE_GLFW_OPENGL3=ON \
#                -DHELLOIMGUI_USE_GLAD=ON         \
#                -DHELLOIMGUI_BUILD_DOCS=ON       \
#                ..
#    - name: Build
#      working-directory: build
#      run: |
#          make
