name: Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

#    - name: Setup ANDROID_NDK_HOME env variable
#      run : |
#        echo "::set-env name=ANDROID_NDK_HOME::/usr/local/lib/android/sdk/ndk-bundle/"

#    - name: Check ANDROID_NDK_HOME env variable
#      run : echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"

# Disabled, not used until we produce an apk
#    - name: Install openjdk-8
#      run: |
#          which java || true
#          echo $JAVA_HOME
#          sudo apt-get install -y openjdk-8-jdk-headless
#          which java || true
#          echo $JAVA_HOME

#    - name: Install SDL for android via vcpkg
#      run: ./tools/sdl_download.sh

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v2

    - name: Configure & build arm64-android
      run: |
          mkdir build_gradle_project
          cd build_gradle_project
          export ANDROID_HOME=/usr/local/lib/android/sdk
          cmake .. -DHELLOIMGUI_CREATE_ANDROID_STUDIO_PROJECT=ON
          cd hello_imgui_demodocking_AndroidStudio
          ./gradlew build
