name: Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Setup ANDROID_NDK_HOME env variable
      run : |
        echo "::set-env name=ANDROID_NDK_HOME::/usr/local/lib/android/sdk/ndk-bundle/"

    - name: Check ANDROID_NDK_HOME env variable
      run : echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"

# Disabled, not used until we produce an apk
#    - name: Install openjdk-8
#      run: |
#          which java || true
#          echo $JAVA_HOME
#          sudo apt-get install -y openjdk-8-jdk-headless
#          which java || true
#          echo $JAVA_HOME

#    Disabled, there is already a sdk at /usr/local/lib/android
#    - name: Download Android NDK
#      run: |
#          mkdir toolchains
#          cd toolchains
#          wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
#          unzip android-ndk-r21d-linux-x86_64.zip
#          cd ..

    - name: Install SDL for android via vcpkg
      run: ./tools/android/vcpkg_install_sdl_android.sh

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v2

    - name: Configure & build arm64-android
      run: |
          ./tools/android/cmake_arm64-android.sh
          cd build_arm64-android
          make -j 4
          cd ..
